apiVersion: v1
kind: ConfigMap
metadata:
  name: php-fpm
data:
  php.ini: |
    TIMEZONE='Europe/Zurich'
  zz-docker.conf: |
    [global]
    daemonize = no
    pid = /tmp/php-fpm.pid
    error_log = /proc/self/fd/2

    [www]
    listen = [::]:9000
    access.log = /proc/self/fd/2

    clear_env = no

    ; Ensure worker stdout and stderr are sent to the main error log.
    catch_workers_output = yes
