apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: redis-secret
    literals:
      - PASSWORD=SECURE_REDIS_PASS
    type: Opaque

resources:
  - deployment.yaml
  - service.yaml
